data_file: "challenge_data.csv"
params:
  Bremen: { A: 2.8, B: -37.0, C: 6.25, D: 0.06, K: 25000 }
  Oldenburg: { A: 3.5, B: -38.2, C: 4.00, D: 0.17, K: 18000 }
temperature_expectation:
  Bremen: [8.3, 12.9, 15.9]
  Oldenburg: [8.1, 12.5, 15.6]
initial_prices:
  TTF: [13.844, 14.009, 14.132]
  GPL: [14.394, 14.309, 14.395]
confidence_level: 0.95
holding_period: 3
